services:
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WP_DIR: ${WP_DIR}
    depends_on: [db]
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WP_ENVIRONMENT_TYPE: local
      WP_DEBUG: true
    ports:
      - "8080:80"
  db:
    image: mysql:8.0.28
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - '3306:3306'
